//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Elis.Rossum.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Elis.Rossum.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Username or Email 的本地化字符串。
        /// </summary>
        public static string activity_auth_hint {
            get {
                return ResourceManager.GetString("activity_auth_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string activity_auth_username {
            get {
                return ResourceManager.GetString("activity_auth_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileURL 的本地化字符串。
        /// </summary>
        public static string activity_exportfile_file {
            get {
                return ResourceManager.GetString("activity_exportfile_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL to file to get data from 的本地化字符串。
        /// </summary>
        public static string activity_exportfile_file_hint {
            get {
                return ResourceManager.GetString("activity_exportfile_file_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string activity_exportfile_key {
            get {
                return ResourceManager.GetString("activity_exportfile_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API key from auth activitity 的本地化字符串。
        /// </summary>
        public static string activity_exportfile_key_hint {
            get {
                return ResourceManager.GetString("activity_exportfile_key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queue 的本地化字符串。
        /// </summary>
        public static string activity_exportfile_queue {
            get {
                return ResourceManager.GetString("activity_exportfile_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queue to export data from 的本地化字符串。
        /// </summary>
        public static string activity_exportfile_queue_hint {
            get {
                return ResourceManager.GetString("activity_exportfile_queue_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string activity_getqueues_key {
            get {
                return ResourceManager.GetString("activity_getqueues_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API key from auth activitity 的本地化字符串。
        /// </summary>
        public static string activity_getqueues_key_hint {
            get {
                return ResourceManager.GetString("activity_getqueues_key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileURL 的本地化字符串。
        /// </summary>
        public static string activity_getstatus_file {
            get {
                return ResourceManager.GetString("activity_getstatus_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL to file to get status from 的本地化字符串。
        /// </summary>
        public static string activity_getstatus_file_hint {
            get {
                return ResourceManager.GetString("activity_getstatus_file_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string activity_getstatus_key {
            get {
                return ResourceManager.GetString("activity_getstatus_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API key from auth activitity 的本地化字符串。
        /// </summary>
        public static string activity_getstatus_key_hint {
            get {
                return ResourceManager.GetString("activity_getstatus_key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename 的本地化字符串。
        /// </summary>
        public static string activity_uploadfile_filename {
            get {
                return ResourceManager.GetString("activity_uploadfile_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File to upload to the queue 的本地化字符串。
        /// </summary>
        public static string activity_uploadfile_filename_hint {
            get {
                return ResourceManager.GetString("activity_uploadfile_filename_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string activity_uploadfile_key {
            get {
                return ResourceManager.GetString("activity_uploadfile_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API key from auth activitity 的本地化字符串。
        /// </summary>
        public static string activity_uploadfile_key_hint {
            get {
                return ResourceManager.GetString("activity_uploadfile_key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queue 的本地化字符串。
        /// </summary>
        public static string activity_uploadfile_queue {
            get {
                return ResourceManager.GetString("activity_uploadfile_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queue to upload the file to 的本地化字符串。
        /// </summary>
        public static string activity_uploadfile_queue_hint {
            get {
                return ResourceManager.GetString("activity_uploadfile_queue_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileURL 的本地化字符串。
        /// </summary>
        public static string activity_waitforfile_file {
            get {
                return ResourceManager.GetString("activity_waitforfile_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL to file to wait for 的本地化字符串。
        /// </summary>
        public static string activity_waitforfile_file_hint {
            get {
                return ResourceManager.GetString("activity_waitforfile_file_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string activity_waitforfile_key {
            get {
                return ResourceManager.GetString("activity_waitforfile_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API key from auth activitity 的本地化字符串。
        /// </summary>
        public static string activity_waitforfile_key_hint {
            get {
                return ResourceManager.GetString("activity_waitforfile_key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string activity_waitforfile_status {
            get {
                return ResourceManager.GetString("activity_waitforfile_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status to wait for 的本地化字符串。
        /// </summary>
        public static string activity_waitforfile_status_hint {
            get {
                return ResourceManager.GetString("activity_waitforfile_status_hint", resourceCulture);
            }
        }
    }
}
