//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Windows.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Windows.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight 的本地化字符串。
        /// </summary>
        public static string detector_button_highlight {
            get {
                return ResourceManager.GetString("detector_button_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Selector 的本地化字符串。
        /// </summary>
        public static string detector_button_open_selector {
            get {
                return ResourceManager.GetString("detector_button_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string detector_button_select {
            get {
                return ResourceManager.GetString("detector_button_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string detector_name {
            get {
                return ResourceManager.GetString("detector_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector 的本地化字符串。
        /// </summary>
        public static string detector_selector {
            get {
                return ResourceManager.GetString("detector_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable caching of elements for faster automation at the expense of ram 的本地化字符串。
        /// </summary>
        public static string enable_cache_help {
            get {
                return ResourceManager.GetString("enable_cache_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop activity 的本地化字符串。
        /// </summary>
        public static string getelement_drop_hint {
            get {
                return ResourceManager.GetString("getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight 的本地化字符串。
        /// </summary>
        public static string getelement_highlight {
            get {
                return ResourceManager.GetString("getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Selector 的本地化字符串。
        /// </summary>
        public static string getelement_open_selector {
            get {
                return ResourceManager.GetString("getelement_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow child searching 的本地化字符串。
        /// </summary>
        public static string plugin_allow_child_searching {
            get {
                return ResourceManager.GetString("plugin_allow_child_searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If an element in a selector is not found, automaticly search all children for match 的本地化字符串。
        /// </summary>
        public static string plugin_allow_child_searching_help {
            get {
                return ResourceManager.GetString("plugin_allow_child_searching_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow multiple hits 的本地化字符串。
        /// </summary>
        public static string plugin_allow_multiple_hits {
            get {
                return ResourceManager.GetString("plugin_allow_multiple_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow an element selector in a selector to find more than one child 的本地化字符串。
        /// </summary>
        public static string plugin_allow_multiple_hits_help {
            get {
                return ResourceManager.GetString("plugin_allow_multiple_hits_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable caching 的本地化字符串。
        /// </summary>
        public static string plugin_enable_cache {
            get {
                return ResourceManager.GetString("plugin_enable_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enum properties 的本地化字符串。
        /// </summary>
        public static string plugin_enum_properties {
            get {
                return ResourceManager.GetString("plugin_enum_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test each selector element for the minimum required amount of properties needed 的本地化字符串。
        /// </summary>
        public static string plugin_enum_properties_help {
            get {
                return ResourceManager.GetString("plugin_enum_properties_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get elements in different thread 的本地化字符串。
        /// </summary>
        public static string plugin_get_elements_in_different_thread {
            get {
                return ResourceManager.GetString("plugin_get_elements_in_different_thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetElement uses another thread while searching, to avoid locks if selector finds robot 的本地化字符串。
        /// </summary>
        public static string plugin_get_elements_in_different_thread_help {
            get {
                return ResourceManager.GetString("plugin_get_elements_in_different_thread_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search descendants 的本地化字符串。
        /// </summary>
        public static string plugin_search_descendants {
            get {
                return ResourceManager.GetString("plugin_search_descendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search all descendants, use for more simple selectors but is slower 的本地化字符串。
        /// </summary>
        public static string plugin_search_descendants_help {
            get {
                return ResourceManager.GetString("plugin_search_descendants_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traverse selector both ways 的本地化字符串。
        /// </summary>
        public static string plugin_traverse_selector_both_ways {
            get {
                return ResourceManager.GetString("plugin_traverse_selector_both_ways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traverse UI tree both ways to filter out ghost selector elements 的本地化字符串。
        /// </summary>
        public static string plugin_traverse_selector_both_ways_help {
            get {
                return ResourceManager.GetString("plugin_traverse_selector_both_ways_help", resourceCulture);
            }
        }
    }
}
