//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add variables 的本地化字符串。
        /// </summary>
        public static string activity_add_variables {
            get {
                return ResourceManager.GetString("activity_add_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double-click to view 的本地化字符串。
        /// </summary>
        public static string activity_click_to_view {
            get {
                return ResourceManager.GetString("activity_click_to_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop activity 的本地化字符串。
        /// </summary>
        public static string activity_drop_hint {
            get {
                return ResourceManager.GetString("activity_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight 的本地化字符串。
        /// </summary>
        public static string activity_highlight {
            get {
                return ResourceManager.GetString("activity_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Selector 的本地化字符串。
        /// </summary>
        public static string activity_open_selector {
            get {
                return ResourceManager.GetString("activity_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Element 的本地化字符串。
        /// </summary>
        public static string activity_select_element {
            get {
                return ResourceManager.GetString("activity_select_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Animate Mouse 的本地化字符串。
        /// </summary>
        public static string animatemouse {
            get {
                return ResourceManager.GetString("animatemouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser addons 的本地化字符串。
        /// </summary>
        public static string browseraddons {
            get {
                return ResourceManager.GetString("browseraddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel key 的本地化字符串。
        /// </summary>
        public static string cancelkey {
            get {
                return ResourceManager.GetString("cancelkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chrome 的本地化字符串。
        /// </summary>
        public static string chrome {
            get {
                return ResourceManager.GetString("chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Click PostWait 的本地化字符串。
        /// </summary>
        public static string clickpostwait {
            get {
                return ResourceManager.GetString("clickpostwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        public static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detectors 的本地化字符串。
        /// </summary>
        public static string detectors {
            get {
                return ResourceManager.GetString("detectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging 的本地化字符串。
        /// </summary>
        public static string dock_logging {
            get {
                return ResourceManager.GetString("dock_logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        public static string dock_output {
            get {
                return ResourceManager.GetString("dock_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        public static string dock_properties {
            get {
                return ResourceManager.GetString("dock_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snippets 的本地化字符串。
        /// </summary>
        public static string dock_snippets {
            get {
                return ResourceManager.GetString("dock_snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolbox 的本地化字符串。
        /// </summary>
        public static string dock_toolbox {
            get {
                return ResourceManager.GetString("dock_toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit Application 的本地化字符串。
        /// </summary>
        public static string exitapplication {
            get {
                return ResourceManager.GetString("exitapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files 的本地化字符串。
        /// </summary>
        public static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firefox 的本地化字符串。
        /// </summary>
        public static string firefox {
            get {
                return ResourceManager.GetString("firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging 的本地化字符串。
        /// </summary>
        public static string logging {
            get {
                return ResourceManager.GetString("logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record directly into designer 的本地化字符串。
        /// </summary>
        public static string main_settings_recording_add_to_designer {
            get {
                return ResourceManager.GetString("main_settings_recording_add_to_designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string mainnew {
            get {
                return ResourceManager.GetString("mainnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenRPA 的本地化字符串。
        /// </summary>
        public static string maintitle {
            get {
                return ResourceManager.GetString("maintitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string minimize {
            get {
                return ResourceManager.GetString("minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Project 的本地化字符串。
        /// </summary>
        public static string newproject {
            get {
                return ResourceManager.GetString("newproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Workflow 的本地化字符串。
        /// </summary>
        public static string newworkflow {
            get {
                return ResourceManager.GetString("newworkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NodeRED 的本地化字符串。
        /// </summary>
        public static string nodered {
            get {
                return ResourceManager.GetString("nodered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created at 的本地化字符串。
        /// </summary>
        public static string open_created {
            get {
                return ResourceManager.GetString("open_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created by 的本地化字符串。
        /// </summary>
        public static string open_createdby {
            get {
                return ResourceManager.GetString("open_createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string open_edit {
            get {
                return ResourceManager.GetString("open_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit XAML 的本地化字符串。
        /// </summary>
        public static string open_edit_xaml {
            get {
                return ResourceManager.GetString("open_edit_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last modified at 的本地化字符串。
        /// </summary>
        public static string open_modified {
            get {
                return ResourceManager.GetString("open_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last modified by 的本地化字符串。
        /// </summary>
        public static string open_modifiedby {
            get {
                return ResourceManager.GetString("open_modifiedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string open_name {
            get {
                return ResourceManager.GetString("open_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Project 的本地化字符串。
        /// </summary>
        public static string open_project {
            get {
                return ResourceManager.GetString("open_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serializable 的本地化字符串。
        /// </summary>
        public static string open_serializable {
            get {
                return ResourceManager.GetString("open_serializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        public static string open_state {
            get {
                return ResourceManager.GetString("open_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Workflow 的本地化字符串。
        /// </summary>
        public static string open_workflow {
            get {
                return ResourceManager.GetString("open_workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlow 的本地化字符串。
        /// </summary>
        public static string openflow {
            get {
                return ResourceManager.GetString("openflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenRPA 的本地化字符串。
        /// </summary>
        public static string openrpa {
            get {
                return ResourceManager.GetString("openrpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packages 的本地化字符串。
        /// </summary>
        public static string packages {
            get {
                return ResourceManager.GetString("packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permissions 的本地化字符串。
        /// </summary>
        public static string permissions {
            get {
                return ResourceManager.GetString("permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string permissions_delete {
            get {
                return ResourceManager.GetString("permissions_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke 的本地化字符串。
        /// </summary>
        public static string permissions_invoke {
            get {
                return ResourceManager.GetString("permissions_invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read 的本地化字符串。
        /// </summary>
        public static string permissions_read {
            get {
                return ResourceManager.GetString("permissions_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string permissions_update {
            get {
                return ResourceManager.GetString("permissions_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string permissionswindow_delete {
            get {
                return ResourceManager.GetString("permissionswindow_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string permissionswindow_new {
            get {
                return ResourceManager.GetString("permissionswindow_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins 的本地化字符串。
        /// </summary>
        public static string plugins {
            get {
                return ResourceManager.GetString("plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record 的本地化字符串。
        /// </summary>
        public static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recorder plugins 的本地化字符串。
        /// </summary>
        public static string recorderplugins {
            get {
                return ResourceManager.GetString("recorderplugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording Overlay 的本地化字符串。
        /// </summary>
        public static string recordingoverlay {
            get {
                return ResourceManager.GetString("recordingoverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string ribbon_search {
            get {
                return ResourceManager.GetString("ribbon_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run plugins 的本地化字符串。
        /// </summary>
        public static string runplugins {
            get {
                return ResourceManager.GetString("runplugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime 的本地化字符串。
        /// </summary>
        public static string runtime {
            get {
                return ResourceManager.GetString("runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector 的本地化字符串。
        /// </summary>
        public static string selector {
            get {
                return ResourceManager.GetString("selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector Verbose 的本地化字符串。
        /// </summary>
        public static string selectorverbose {
            get {
                return ResourceManager.GetString("selectorverbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings File 的本地化字符串。
        /// </summary>
        public static string settingsfile {
            get {
                return ResourceManager.GetString("settingsfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signout 的本地化字符串。
        /// </summary>
        public static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slow Motion 的本地化字符串。
        /// </summary>
        public static string slowmotion {
            get {
                return ResourceManager.GetString("slowmotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected 的本地化字符串。
        /// </summary>
        public static string status_disconnected {
            get {
                return ResourceManager.GetString("status_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tesseract 的本地化字符串。
        /// </summary>
        public static string tesseract {
            get {
                return ResourceManager.GetString("tesseract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小摩 RPA 的本地化字符串。
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Type 的本地化字符串。
        /// </summary>
        public static string tools_change_type {
            get {
                return ResourceManager.GetString("tools_change_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swap SendKeys 的本地化字符串。
        /// </summary>
        public static string tools_swap_sendkeys {
            get {
                return ResourceManager.GetString("tools_swap_sendkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swap Virtual Clicking 的本地化字符串。
        /// </summary>
        public static string tools_swap_virtualclick {
            get {
                return ResourceManager.GetString("tools_swap_virtualclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use SendKeys 的本地化字符串。
        /// </summary>
        public static string usesendkeys {
            get {
                return ResourceManager.GetString("usesendkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Virtual Clicks 的本地化字符串。
        /// </summary>
        public static string usevirtualclicks {
            get {
                return ResourceManager.GetString("usevirtualclicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verbose 的本地化字符串。
        /// </summary>
        public static string verbose {
            get {
                return ResourceManager.GetString("verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visual Tracking 的本地化字符串。
        /// </summary>
        public static string visualtracking {
            get {
                return ResourceManager.GetString("visualtracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
