//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.AviRecorder.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.AviRecorder.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Double-click to view 的本地化字符串。
        /// </summary>
        public static string activity_click_to_view {
            get {
                return ResourceManager.GetString("activity_click_to_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play this video file 的本地化字符串。
        /// </summary>
        public static string activity_play_hint {
            get {
                return ResourceManager.GetString("activity_play_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save in this folder 的本地化字符串。
        /// </summary>
        public static string activity_start_hint {
            get {
                return ResourceManager.GetString("activity_start_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save video filename 的本地化字符串。
        /// </summary>
        public static string activity_stop_hint {
            get {
                return ResourceManager.GetString("activity_stop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Codec 的本地化字符串。
        /// </summary>
        public static string plugin_codec {
            get {
                return ResourceManager.GetString("plugin_codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string plugin_enabled {
            get {
                return ResourceManager.GetString("plugin_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep successful 的本地化字符串。
        /// </summary>
        public static string plugin_keep_successful {
            get {
                return ResourceManager.GetString("plugin_keep_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording quality 的本地化字符串。
        /// </summary>
        public static string plugin_quality {
            get {
                return ResourceManager.GetString("plugin_quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save in folder 的本地化字符串。
        /// </summary>
        public static string plugin_save_in_folder {
            get {
                return ResourceManager.GetString("plugin_save_in_folder", resourceCulture);
            }
        }
    }
}
